name: sinitaivas-live-validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - develop
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv lock
          pipenv verify
          pipenv install --dev
      - name: Validate
        run: |
          pipenv run type
          pipenv run validate
          pipenv run scan
      - name: Test with pytest
        run: |
          pipenv run pytest tests/

      - name: Generate coverage report
        if: success()
        run: |
          pipenv run coverage run -m pytest
          pipenv run coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        if: success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
